// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnDemandApp.Infrastructure.Data;

#nullable disable

namespace on_demand_app.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210080809_AddProviderOnboardingFields2")]
    partial class AddProviderOnboardingFields2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnDemandApp.Core.Entities.AuthCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose", "Code");

                    b.ToTable("AuthCodes");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.LocationPing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AccuracyM")
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("numeric(10,6)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProviderId");

                    b.ToTable("LocationPings");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("JobId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PSPPaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PSPProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PSPProvider", "PSPPaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ProviderProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CAMoisCourant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ObjectifMensuelCA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RayonKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("ProviderProfiles");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ProviderService", b =>
                {
                    b.Property<int>("ProviderServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderServiceId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProviderProfileUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("int");

                    b.HasKey("ProviderServiceId");

                    b.HasIndex("ProviderProfileUserId");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("ProviderServices");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Icon = "🏠",
                            Name = "Services à domicile"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Icon = "💇",
                            Name = "Beauté et bien-être"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Icon = "🚗",
                            Name = "Services automobiles"
                        });
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ServiceItems");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 1,
                            Icon = "🚰",
                            Name = "Plombier",
                            Slug = "plombier"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 1,
                            Icon = "💡",
                            Name = "Électricien",
                            Slug = "electricien"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 1,
                            Icon = "🧹",
                            Name = "Ménage",
                            Slug = "menage"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 1,
                            Icon = "🎨🔧",
                            Name = "Peintre / bricoleur",
                            Slug = "peintre-bricoleur"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 1,
                            Icon = "🌿",
                            Name = "Jardinier",
                            Slug = "jardinier"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 1,
                            Icon = "⚙️",
                            Name = "Technicien électroménager",
                            Slug = "technicien-electromenager"
                        },
                        new
                        {
                            Id = 201,
                            CategoryId = 2,
                            Icon = "💇",
                            Name = "Coiffeur(se)",
                            Slug = "coiffeur"
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 2,
                            Icon = "💅",
                            Name = "Esthéticien(ne)",
                            Slug = "estheticienne"
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 2,
                            Icon = "💆",
                            Name = "Masseur / masseuse",
                            Slug = "masseur"
                        },
                        new
                        {
                            Id = 204,
                            CategoryId = 2,
                            Icon = "🏋️‍♀️",
                            Name = "Coach sportif",
                            Slug = "coach-sportif"
                        },
                        new
                        {
                            Id = 205,
                            CategoryId = 2,
                            Icon = "🍎",
                            Name = "Nutritionniste",
                            Slug = "nutritionniste"
                        },
                        new
                        {
                            Id = 301,
                            CategoryId = 3,
                            Icon = "🛠️",
                            Name = "Mécanicien à domicile",
                            Slug = "mecanicien-domicile"
                        },
                        new
                        {
                            Id = 302,
                            CategoryId = 3,
                            Icon = "🚘",
                            Name = "Lavage auto à domicile",
                            Slug = "lavage-auto-domicile"
                        },
                        new
                        {
                            Id = 303,
                            CategoryId = 3,
                            Icon = "🚛",
                            Name = "Dépanneur / remorquage",
                            Slug = "depannage-remorquage"
                        },
                        new
                        {
                            Id = 304,
                            CategoryId = 3,
                            Icon = "🚕",
                            Name = "Chauffeur privé (VTC, taxi)",
                            Slug = "chauffeur-prive"
                        });
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.AuthCode", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Job", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.User", "Client")
                        .WithMany("JobsRequested")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnDemandApp.Core.Entities.User", "Provider")
                        .WithMany("JobsTaken")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnDemandApp.Core.Entities.Service", "Service")
                        .WithMany("Jobs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.LocationPing", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandApp.Core.Entities.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Message", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnDemandApp.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandApp.Core.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Job");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Payment", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ProviderProfile", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.User", "User")
                        .WithOne("ProviderProfile")
                        .HasForeignKey("OnDemandApp.Core.Entities.ProviderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ProviderService", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.ProviderProfile", "ProviderProfile")
                        .WithMany("Services")
                        .HasForeignKey("ProviderProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandApp.Core.Entities.ServiceItem", "ServiceItem")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderProfile");

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Service", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ServiceItem", b =>
                {
                    b.HasOne("OnDemandApp.Core.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ProviderProfile", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.Service", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.ServiceItem", b =>
                {
                    b.Navigation("ProviderServices");
                });

            modelBuilder.Entity("OnDemandApp.Core.Entities.User", b =>
                {
                    b.Navigation("JobsRequested");

                    b.Navigation("JobsTaken");

                    b.Navigation("ProviderProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
